### ISSUE TITLE
Waffle batter still present in maker

### ISSUE THREAD

**Issue by mazes-80** [GreenXenith/waffles#13]
To trigger this bug my procedure is: repeat close and open waffle maker as fast as I can until I can see the batter while maker is opened.

I didn't look much at why it can happen since I found this issue

**Comment by GreenXenith** [comment]
@mazes-80 I'm not sure I understand. You are supposed to see the batter inside the maker if it is open.

**Comment by mazes-80** [comment]
Yes, it is. My description lack a detail: dig the waffle maker after repeat close open fast

-> the batter still floats there

I just come to reproduce it, and dug with maker closed. At one point after close open cycle: do not dig the maker until batter cooked.

**Comment by GreenXenith** [comment]
Should be fixed with 6ddc42b and 9486f8d.
